blank_issues_enabled: false
contact_links:
  - name: Questions regarding the Project
    about: ğŸ’¡ Report questions about the project here. Melde Fragen zum Projekt hier.
    url: https://github.com/jomjol/AI-on-the-edge-device/discussions
  - name: Firmware Issues
    about: ğŸ Report bugs regarding the firmware here. Melde Fehler mit der Firmware hier.
    url: https://github.com/jomjol/AI-on-the-edge-device/issues
